import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import NavBar from '../components/NavBar'
import styles from '../styles/Home.module.css'
import { FaFacebook, FaTwitch, FaInstagram, FaBriefcase, FaPalette, FaSearchLocation, FaPhone, FaVoicemail, FaLocationArrow, FaEnvelope, FaGithub, FaLink, FaExternalLinkAlt } from 'react-icons/fa';
import api from '../services/api'

import { IProject } from './api/projects'
// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const { data } = await api.get('/projects');

  // Pass data to the page via props
  return { props: { data } }
}


const Home: NextPage<{ data: IProject[] }> = ({ data }) => {

  console.log({ data });
  

  return (
    <div className="container-fluid px-0">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <NavBar />

        <div className="container-fluid bg-dark py-5">
            <div className="row align-items-center px-md-5">
              <div className="col-12 col-md-6 order-1 order-sm-2">
                <div className="row justify-content-end px-4">
                  <Image alt='image-profile' src="/images/pic.png" className="img-fluid" width={569} height={555} />
                </div>
              </div>
              <div className="col-12 col-md-6 order-2 order-sm-1">
                <div className="row justify-content-start">
                  <div className="card border-0 bg-transparent text-white">
                    <div className="card-header bg-transparent border-0 app-text-primary">
                      Mateus Arenas
                    </div>
                    <div className="card-body">
                      <h1 className="card-title">Sobre</h1>
                      <p className="card-text">Sou um Desenvolvedor de Sistemas Web e Mobile, tendo como foco principal a linguagem Javascript/ Typescript e o Freamework React Native. Faço construções de APIs utilizando Node Js e MongoDB. Atualmente trabalho com Freelancer e estou em fase de conclusão de estudos em Analise e Desenvolvedor de Sistemas.</p>
                      <Link href={"#projects"}>
                        <a className="btn btn-primary app-bg-primary border-0">Veja meus projetos</a>
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
        </div>
      </div>

      <div className="container py-4 mt-5">
          <div className="text-center mb-4 app-text-primary">Habilidades</div>
          <h2 className="text-center">Qualificações</h2>

          <div className="row align-items-center mt-5">

            <div className="col-12 col-md-6">
              <div className="card p-4">
                <div className="card-body">
                  <div className="d-flex flex-row align-items-center">
                    <span className="app-icon-btn rounded-circle">
                      <FaPalette />
                    </span>
                    <h3 className="card-title p-4">
                      Design
                    </h3>
                  </div>
                  <p className="card-text">Agency is a business you hire to outsource your digital marketing efforts, instead of handling in-house.</p>
                  <Link href={"#"}><a className="text-decoration-none app-text-primary p-0">Learn More</a></Link>
                </div>
              </div>
            </div>
            <div className="col-12 col-md-6">
              <div className="card p-4">
                <div className="card-body">
                <div className="d-flex flex-row align-items-center">
                    <span className="app-icon-btn rounded-circle">
                      <FaBriefcase />
                    </span>
                    <h3 className="card-title p-4">
                      Design
                    </h3>
                  </div>
                  <p className="card-text">Agency is a business you hire to outsource your digital marketing efforts, instead of handling in-house.</p>
                  <Link href={"#"}><a className="text-decoration-none app-text-primary p-0">Learn More</a></Link>
                </div>
              </div>
            </div>


          </div>
          <div className="row text-center align-items-center py-4 mt-5">
            <p>Want more service? <Link href={"#"}><a className="text-decoration-none app-text-primary p-0">Explore Now</a></Link></p>
          </div>
      </div>

      <div id='projects' className="container-fluid bg-dark">
        <div className="container py-5">

          <div className="row py-5 align-items-center">
            <div className="col-12 col-md-6">
              <p className="app-text-primary">Portfolio</p>
              <h2 className="text-white">Últimos projetos</h2>
            </div>
            <div className="col-12 col-md-6">
              <button type="button" className="btn btn-outline-light float-end">Veja Mais</button>
            </div>
          </div>

          <div  className="row py-4">
            {data?.slice(0, 4)?.map(item => (
              <Link key={item?.title} passHref shallow href={item?.link}>
                <a target="_blank" rel="noopener noreferrer" className="col-12 col-md-6 col-lg-3 p-2 text-decoration-none">
                  <div className="card overflow-hidden bg-dark text-white w-100 h-100">
                    {/* <div className='d-flex align-items-center justify-content-center bg-secondary rounded-end w-100 h-100 position-relative overflow-hidden' style={{ aspectRatio: "16/16" }}> */}
                                      {/* <p className='text-white'>{item?._id}</p> */}
                                      {/* <Image alt='product-img' src="/images/default-product.webp" objectFit="cover" layout="fill" width={1080} height={720} /> */}
                                    {/* </div> */}
                      <div className="row g-0 h-100 w-100" style={{ aspectRatio: "16/14" }}>
                        <div className="col-6 position-relative">
                          <Image alt={item?.title + '1'} src={item?.image1} className="card-img rounded-0" objectFit="cover" layout="fill" width={1080} height={720} />
                        </div>
                        <div className="col-6 position-relative">
                          <Image alt={item?.title + '2'} src={item?.image2} className="card-img rounded-0" objectFit="cover" layout="fill" width={1080} height={720} />
                        </div>
                      </div>

                    <div className="card-body d-flex flex-column justify-content-end p-3 py-4">
                      <div className="d-flex flex-row justify-content-between align-items-center mb-3">
                        <div>
                          <span className="badge rounded-pill bg-light text-dark p-2">{item?.usage}</span>
                        </div>
                        <div className="d-flex flex-row justify-content-between align-items-center">
                          <Link passHref shallow href={item?.github || ""}>
                            <a className="text-white me-3" target="_blank">
                              <FaGithub size={20} />
                            </a>
                          </Link>
                          <Link passHref shallow href={item?.link || ""}>
                            <a className="text-white" target="_blank">
                              <FaExternalLinkAlt size={20} />
                            </a>
                          </Link>
                        </div>
                      </div>
                      <h5 className="card-title">{item?.title}</h5>
                    </div>
                  </div>
                </a>
              </Link>
            ))}

          </div>
        </div>
      </div>


      <div className="container my-5">
        <div className="row py-4 align-items-center">
          <div className="col-12 col-md-6">
            <Image alt='pro' src={'/images/pic-about.png'} width={529} height={521} />
          </div>
          <div className="col-12 col-md-6">
            <div className="card border-0 bg-transparent">
              <div className="card-header bg-transparent border-0 app-text-primary">
                Mateus Arenas
              </div>
              <div className="card-body">
                <h1 className="card-title">Professional <br/> Web Designer</h1>
                <h5>Provides a full service range</h5>
                <p className="card-text">Ability to put themselves in the merchants shoes. It is meant to partner on the long run, and work as an extension of the merchants team.</p>
                <Link href={"#"}>
                  <a className="btn app-text-primary app-border-primary">About me</a>
                </Link>
              </div>
            </div>
          </div>
        </div>
      </div>


      <div className="bg-dark my-5">
        <div className="container py-5">
          <div className="row py-5 align-items-center">

            <div className="col-12 col-md-6 p-3 p-md-5 order-md-2 order-sm-1">
              <div className="card border-0 text-white bg-transparent">
                <div className="card-header bg-transparent border-0 app-text-primary">
                  CONTACT
                </div>
                <div className="card-body mb-4">
                  <h1 className="card-title">Contact Me</h1>
                  <p className="card-text">A digital agency is a business you hire to outsource your digital marketing efforts, instead of handling in-house.</p>
                </div>
                <ul className="list-group list-group-flush border-0 mb-5">
                  <li className="list-group-item bg-transparent text-white border-0 mb-3">
                    <span className="app-icon-btn rounded-circle me-3">
                      <FaLocationArrow />
                    </span>
                    2247 Lunetta Street, TX 76301
                  </li>
                  <li className="list-group-item bg-transparent text-white border-0 mb-3">
                    <span className="app-icon-btn rounded-circle me-3">
                      <FaPhone />
                    </span>
                    +1 (234) 567-89-00
                  </li>
                  <li className="list-group-item bg-transparent text-white border-0 mb-3">
                    <span className="app-icon-btn rounded-circle me-3">
                      <FaEnvelope />
                    </span>
                    info@agency.com
                  </li>
                </ul>
              </div>
            </div>

            <div className="col-12 col-md-6 p-3 p-md-5 order-md-1 order-sm-2">
              <form className="row g-3 bg-white p-4 py-5 rounded">

                <div className="col-12">
                  <h3>Get In Touch</h3>
                </div>

                <div className="col-12 form-floating mb-3">
                  <input type="email" className="form-control" id="floatingInput" placeholder="name@example.com" />
                  <label className="ps-3" htmlFor="floatingInput">Email address</label>
                </div>
                
                <div className="col-12 form-floating">
                  <select className="form-select" id="floatingSelectGrid">
                    <option selected>Open this select menu</option>
                    <option value="1">One</option>
                    <option value="2">Two</option>
                    <option value="3">Three</option>
                  </select>
                  <label className="ps-3" htmlFor="floatingSelectGrid">Works with selects</label>
                </div>

                <div className="col-12 form-floating">
                  <textarea className="form-control" placeholder="Leave a comment here" id="floatingTextarea2" style={{ height: 100 }} />
                  <label className="ps-3" htmlFor="floatingTextarea2">Comments</label>
                </div>

                <div className="col-12">
                  <button type="submit" className="btn app-bg-primary text-white float-end mt-4">Submit Now</button>
                </div>

              </form>
            </div>

          </div>
        </div>
      </div>


      <footer className="bd-footer pt-4 pt-md-5 mt-5 bg-light">
        <div className="container py-4 pt-md-5 px-4 px-md-3">
          <div className="row">
            <div className="col-lg-3 mb-3">
              <a className="d-inline-flex align-items-center mb-2 link-dark text-decoration-none" aria-label="Bootstrap">
                {/* <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" className="d-block me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg> */}
                <span className="fs-5">Personal</span>
              </a>
            </div>
            <div className="col-6 col-lg-3 offset-lg-1 mb-3">
              <h5 className="mb-4">Menu</h5>
              <ul className="list-unstyled">
                <li className="mb-2"><a>About</a></li>
                <li className="mb-2"><a>Services</a></li>
                <li className="mb-2"><a>Blog</a></li>
                <li className="mb-2"><a>Contact</a></li>
              </ul>
            </div>
            <div className="col-6 col-lg-3 mb-3">
              <h5 className="mb-4">Service</h5>
              <ul className="list-unstyled">
                <li className="mb-2"><a>Design</a></li>
                <li className="mb-2"><a>Devlopment</a></li>
                <li className="mb-2"><a>Marketing</a></li>
                <li className="mb-2"><a>See More</a></li>
              </ul>
            </div>
            <div className="col-6 col-lg-2 mb-3">
              <ul className="list-unstyled row">
                <li className="mb-2 col-4">
                  <a>
                    <FaFacebook size={24*2} />
                  </a>
                </li>
                <li className="mb-2 col-4">
                  <a>
                    <FaTwitch size={24*2} />
                  </a>
                </li>
                <li className="mb-2 col-4">
                  <a>
                    <FaInstagram size={24*2} />
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <hr className="border-2 opacity-50"/>
          <div className="row mt-5">
            
            <div className="col-12 col-md-6">
              <p>Copyright © 2022 Laaqiq. All Rights Reserved.</p>
            </div>

            <div className="col-12 col-md-6 text-center text-md-end">
              <div className="btn-group col-auto">
                  <a className="nav-link me-2">Terms of Use</a>
                  <a className="nav-link me-2">Privacy Policy</a>
              </div>
            </div>

          </div>
        </div>
      </footer>
    </div>
  )
}

export default Home
